/*
    File: KPLIB_debriefs.inc
    Author: KP Liberation Dev Team - https://github.com/KillahPotatoes
    Date: 2020-05-09
    Last Update: 2020-05-09
    License: MIT License - http://www.opensource.org/licenses/MIT

    Description:
        Debriefing defines for KP Liberation.
*/

class End1 {
    title =	$STR_SORRY;
    subtitle = "";
    description = $STR_COMMANDER_NOT_AUTHORIZED;
    pictureBackground = "";
};

class End2 {
    title =	$STR_SORRY;
    subtitle = "";
    description = $STR_MP_NOT_AUTHORIZED;
    pictureBackground = "";
};

class End3 {
    title =	$STR_SORRY;
    subtitle = "";
    description = $STR_MC_NOT_AUTHORIZED;
    pictureBackground = "";
};